package az.risk.agentx.model.user;

public enum AgentState {
    READY, NOT_READY, LOGIN, LOGOUT, RESERVED, ACTIVE, PAUSED, INTERRUPTED, WORK_READY, WORK_NOT_READY, TALKING, WORK, UNKNOWN, BUSY_OTHER, BUSY, OTHER
}

